server:
  port: 8081
#指定服务处理指定的文件类型
upload:
  filemap:
    # 上传到七牛云的文件类型
#    qiniu: mp4,avi
    aliyun: mp4,avi
    # 上传到本地 MinIO 的文件类型
    minioFileUpload: png,jpg
# MinIO 配置
minio:
  endpoint: http://127.0.0.1:9000
  bucket: bucket1
# 七牛云
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKey: a7i6rXXXXXJdYX2
    accessKeySecret: MeSZPybPHXXXXXXXXXXXXEaUbfRtdH8gl4
    bucketName: sklll
    key: video/
    url: https://sklll.XXXXXXXXXXX.aliyuncs.com/video/ #访问地址配置
#spring:
#  application:
#    name: seckill-goods
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#  servlet:
#    multipart:
#      max-file-size: 100MB #上传文件大小配置
